### PR TITLE
promisifying server start

### PR DESCRIPTION
**Pull request by maxlath**
`americano.start` isn't aware of promises so it needs to be [promisified](http://bluebirdjs.com/docs/api/promisification.html) to stay the consistent with the rest of the code base: having callbacks in the middle of a promise chain is rather ugly and makes things seem hard to refactor

### CODE REVIEW

**Comment by almereyda** [comment]
The same case as in https://github.com/TransforMap/transformap-api/pull/25#issuecomment-186432087 applies. Cannot merge this from here right now, despite it looks nice.

**Comment by maxlath** [comment]
@almereyda I don't get why that would be blocking for this PR

**Comment by almereyda** [comment]
Hmm, in a sense I cannot get `americano.start` to test it, if no further documentation is provided to make it work.

**Comment by almereyda** [comment]
You were right.

My error as of 73a2c36b6a56ea1f96af0f89f70bf0968df9dd97

**Pull request merged**
