### PR TITLE
Documentation, development and deployment dependencies

### LINKED ISSUE #33: Documentation for basic API endpoints
It would be super helpful to have these listed somewhere. Could a quick summary be added to the docs?

### PR DESCRIPTION
**Pull request by almereyda**
This branch includes commits which allow the API to run via Dokku.
It is being achieved by 

It is mergeable when the following features are present:
- [ ] Deployment instructions for `production` and `staging` environments due to a request from @species 
- [x] Basic documentation of API endpoints, fixes #33 
- [ ] extend/rework the README to provide basic information about the API and its' intended purpose within the Transformap broader scope.

Further additions are:
- a `raw` API endpoint that omits GeoJSON validation
- Dokku/herokuish related repository layout
- Improvements to the database initialization script passing generated configuration state
  We may still think of a way to mirror generated credentials external to `stdout`.
- Docker Compose environments for production-like and development scenarios
- a server patch to allow uploads of meaningful size
- a missing dependency

### CODE REVIEW

**Comment by gandhiano** [comment]
I would propose adding a further requirement before getting this merged:
- [ ] extend/rework the README to provide basic information about the API and its' intended purpose within the Transformap broader scope.

**Comment by gandhiano** [comment]
We are still missing basic API usage instructions, which makes it difficult to start using it. @almereyda could you commit to here and close the pull request? Or alternatively @species or @maxlath do it in another PR or directly?

**Comment by species** [comment]
As I want to get started to work on the API again, does it make sense to merge, even if documentation is not yet done 100%?
I don't want to have big merge conflicts later...

**Comment by almereyda** [comment]
@species Yes, go ahead, as this is the currently live version, isn't it?

**Pull request merged**
