### PR TITLE
Auth

### PR DESCRIPTION
**Pull request by maxlath**
# [work in progress, don't merge yet]

setting up a basic authentification system using [passport](http://passportjs.org) and a first authentification strategy: [passport-http](https://github.com/jaredhanson/passport-http)

can be tested like so

``` sh
curl http://jon:wrongpassword@localhost:8726/hello?name=george
# => 401
curl http://jon:dubdubdub@localhost:8726/hello?name=george
# => 200
```

### CODE REVIEW

**Comment by gandhiano** [comment]
This looks promising. 
I would suggest using a similar UUID for users (instead of id), similar to other objects we store in our DB.

Also interested in understanding how to authenticate against other providers, e.g. OpenID Connect or OAuth. I found [this module for OpenID Connect](https://github.com/jaredhanson/passport-openidconnect), but seems unmaintained.

**Comment by gandhiano** [comment]
Is any progress going on here?
We have no user story for authentication (was originally not thought as important, but obviously is), but we should work on it, because it's implementation will be very much defining the workflow and interoperability with other platforms.
For the record, I would very much appreciate that this is coordinate with other [efforts being made here](https://tree.taiga.io/project/gandhiano-degrowth-2016/us/27).

**Comment by almereyda** [comment]
Will we want to use https://github.com/colinskow/superlogin ?

Using a publicly accessible CouchDB could help syncing state with any PouchDB client, like https://github.com/pubkey/rxdb

**Comment by almereyda** [comment]
Deprecated by #48

**Pull request closed without merging**
